### ISSUE TITLE
Documentation does not work.

### ISSUE THREAD

**Issue by Speakus** [Sowapps/orpheus-doc#1]
This link make error: http://orpheus-framework.com/doc/html/

For example I searched about how to solve issue: 'Database configuration not found, define constant PDODEFINSTNAME to set the default instance.'

my configs dir contains the file database.ini with required settings but It looks like orpheus-framework could not see it.

**Comment by Cartman34** [comment]
Thank you for your feedback, the documentation will be fixed soon.

To solve you issue, ensure your configs/database.ini contains the properties driver, dbname, user & passwd with no section and the file permissions allow the web server user to read it.

Do you use any instance.php file to set APPLICATIONPATH or INSTANCEPATH ?

An important update is pending.

**Comment by Speakus** [comment]
Thank you for fast response. I fixed the issue.
1. I used commented line inside database.ini
2. I used INSTANCEPATH to folder up to 'sources/' folder (although this folder contains 'configs/database.ini' too - but it was ignored by the framework for unknown reason...)

So I removed commented line + I stop to use custom INSTANCEPATH. And after these steps code works properly

**Comment by Cartman34** [comment]
There was some works on Orpheus Doc. Now, it's all right.
We changed the doc generator to phpDocumentor and new doc url is : http://doc.orpheus-framework.com/

Paths priorities are : INSTANCEPATH > APPLICATIONPATH > ORPHEUSPATH
INSTANCEPATH is your instance folder, it may contain no source, only configuration.
APPLICATIONPATH is your application folder, it contains your app sources.
ORPHEUSPATH is your Oprheus install folder, you may have it common to multiple apps.
Separating INSTANCEPATH & APPLICATIONPATH is the most common case because it allows you to have no data in your sources folder & to use multiple instances of the same application.

The parent folder of your application may contains an instance.php file which is a php descriptor of your instance (in most cases, it defines DEV_VERSION and INSTANCEPATH).

Now documentation is working, if you get any other trouble, please open a new thread ;-)
